server:
  port: ${SERVER_PORT}
# ${SERVER_PORT} 8762

spring:
  cloud:
    config:
      label: master
      profile: dev

eureka:
  client:
    serviceUrl:
      defaultZone: ${SPRING_EUREKA_SERVER_URI:http://localhost:8761/eureka/}